"""SkillBuilder — generates new skill code via the LLM and saves it.

The agent calls this when it detects a repeated pattern or the user
explicitly asks to save something as a skill.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from typing import Any

from phynai.skills.models import SkillMeta

logger = logging.getLogger("phynai.skills.builder")

# Template for generated skill modules
_SKILL_TEMPLATE = '''\
"""Skill: {name}

{description}

Auto-generated by PhynAI on {date}.
"""

from __future__ import annotations

from typing import Any

from phynai.contracts.tools import Risk, ToolResult
from phynai.tools.decorator import tool


@tool(
    name="{name}",
    description="{description}",
    risk=Risk.{risk},
    mutates={mutates},
    capabilities={capabilities},
    parameters={parameters},
    tags={tags},
)
async def {func_name}(arguments: dict[str, Any]) -> ToolResult:
    import time
    t0 = time.monotonic()

{body}

    return ToolResult(
        tool_name="{name}",
        success=True,
        output=output,
        duration_ms=(time.monotonic() - t0) * 1000,
    )
'''

_SYSTEM_PROMPT = """\
You are a Python code generator for PhynAI skill modules.
Generate ONLY the function body (the lines inside the async function, before the return statement).
The function receives `arguments: dict[str, Any]` and must set a variable `output: str`.
Do not include imports — they go outside the function. Keep it simple and safe.
Use only the Python standard library plus: httpx, pathlib, subprocess (with care).
"""


class SkillBuilder:
    """Creates skill code via LLM and persists to SkillRegistry."""

    def __init__(self, client: Any, registry: Any) -> None:
        self._client = client
        self._registry = registry

    async def build_from_description(
        self,
        name: str,
        description: str,
        example_prompt: str = "",
        risk: str = "LOW",
        mutates: bool = False,
        capabilities: list[str] | None = None,
        parameters: dict[str, Any] | None = None,
        tags: list[str] | None = None,
    ) -> SkillMeta:
        """Ask the LLM to generate a skill, save it, return its metadata."""
        name = _sanitize_name(name)
        func_name = f"{name}_skill"
        params = parameters or {}
        caps = capabilities or []
        tag_list = tags or []

        user_prompt = (
            f"Write the body of a PhynAI skill called `{name}`.\n"
            f"Description: {description}\n"
        )
        if example_prompt:
            user_prompt += f"Example usage: {example_prompt}\n"
        if params:
            user_prompt += f"Parameters (JSON Schema): {json.dumps(params)}\n"
        user_prompt += (
            "\nRespond with ONLY the Python function body lines. "
            "Set `output` to a string result. No def line, no return statement."
        )

        response = await self._client.create_completion(
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ]
        )

        choices = response.get("choices", [])
        body_raw = choices[0].get("message", {}).get("content", "") if choices else ""
        body = _indent(body_raw.strip(), 4)

        code = _SKILL_TEMPLATE.format(
            name=name,
            func_name=func_name,
            description=description,
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            risk=risk.upper(),
            mutates=str(mutates),
            capabilities=repr(caps),
            parameters=json.dumps(params),
            tags=repr(tag_list),
            body=body,
        )

        meta = SkillMeta(
            name=name,
            description=description,
            source="generated",
            tags=tag_list,
            parameters=params,
        )

        self._registry.save_skill(name, code, meta)
        logger.info("Built and saved skill '%s'", name)
        return meta

    async def build_from_conversation(
        self,
        messages: list[dict[str, Any]],
        suggested_name: str = "",
    ) -> SkillMeta | None:
        """Analyse a conversation and extract a reusable skill if one is found.

        Returns the SkillMeta if a skill was extracted, None otherwise.
        """
        summary_prompt = (
            "Review this conversation. If the assistant performed a clearly reusable, "
            "self-contained task, extract it as a PhynAI skill.\n\n"
            "Respond with JSON only:\n"
            '{"should_create": true/false, "name": "snake_case_name", '
            '"description": "one sentence", "body": "python body lines"}\n\n'
            "If the task is not reusable, respond with {\"should_create\": false}.\n\n"
            f"Conversation:\n{_format_messages(messages[-10:])}"
        )

        response = await self._client.create_completion(
            messages=[{"role": "user", "content": summary_prompt}]
        )
        choices = response.get("choices", [])
        raw = choices[0].get("message", {}).get("content", "") if choices else ""

        try:
            data = json.loads(_extract_json(raw))
        except (json.JSONDecodeError, ValueError):
            return None

        if not data.get("should_create"):
            return None

        name = _sanitize_name(suggested_name or data.get("name", "unnamed_skill"))
        description = data.get("description", "Auto-extracted skill")
        body = _indent(data.get("body", '    output = "done"').strip(), 4)

        code = _SKILL_TEMPLATE.format(
            name=name,
            func_name=f"{name}_skill",
            description=description,
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            risk="LOW",
            mutates="False",
            capabilities="[]",
            parameters="{}",
            tags="[]",
            body=body,
        )

        meta = SkillMeta(name=name, description=description, source="generated")
        self._registry.save_skill(name, code, meta)
        logger.info("Extracted skill '%s' from conversation", name)
        return meta


# ── Helpers ───────────────────────────────────────────────────────────────────

def _sanitize_name(name: str) -> str:
    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name or "unnamed_skill"


def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in text.splitlines())


def _format_messages(messages: list[dict[str, Any]]) -> str:
    lines = []
    for m in messages:
        role = m.get("role", "?")
        content = m.get("content") or ""
        if isinstance(content, list):
            content = " ".join(
                b.get("text", "") for b in content if isinstance(b, dict)
            )
        lines.append(f"{role.upper()}: {content[:300]}")
    return "\n".join(lines)


def _extract_json(text: str) -> str:
    """Pull the first {...} block out of a response."""
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return match.group(0) if match else text
